### ISSUE TITLE
error while signin with google auth (for mobile)

### ISSUE THREAD

**Issue by JulienDiTria** [Tarjetakuna/Tarjetakuna#12]
steps done :
- Start app
- click on signin
- click on sign in with google
- choose gmail account
- bug : goes back to signin page without being logged in

insight: 
firebase settings ?

todo:
at least show that there as been an error  with a toast
```
val text = "Hello toast!"
val duration = Toast.LENGTH_SHORT

val toast = Toast.makeText(applicationContext, text, duration)
toast.show()
```

logs : 

03/15 15:44:16: Launching 'MainActivity' on Pixel 2 API 32.
Install successfully finished in 77 ms.
$ adb shell am start -n "com.github.bjolidon.bootcamp/com.github.bjolidon.bootcamp.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 30234 on device 'Pixel_2_API_32 [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/olidon.bootcam: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/olidon.bootcam: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10149; state: ENABLED
V/GraphicsEnvironment: ANGLE Developer option for 'com.github.bjolidon.bootcamp' set to: 'default'
V/GraphicsEnvironment: ANGLE GameManagerService for com.github.bjolidon.bootcamp: false
V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/olidon.bootcam: Class com.google.android.gms.common.api.internal.BackgroundDetector failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
W/olidon.bootcam: Class com.google.firebase.auth.FirebaseAuth failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.internal.firebase-auth-api.zzyz failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.firebase.analytics.connector.AnalyticsConnectorImpl failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.internal.measurement.zzef failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzw failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzr failed lock verification and will run slower.
I/FirebaseInitProvider: FirebaseApp initialization successful
W/olidon.bootcam: Class com.google.android.gms.common.internal.zzag failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.zzn failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.dynamite.zzb failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.dynamite.zza failed lock verification and will run slower.
I/DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:86 and remote module com.google.android.gms.measurement.dynamite:87
I/DynamiteModule: Selected remote version of com.google.android.gms.measurement.dynamite, version >= 87
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/System: ClassLoader referenced unknown path: 
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
D/AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
V/FA: onActivityCreated
V/FA: App measurement collection enabled
V/FA: App measurement enabled for app package, google app id: com.github.bjolidon.bootcamp, 1:977629908956:android:5aa1270f91ef36b7330919
I/FA: App measurement initialized, version: 75024
I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.github.bjolidon.bootcamp
D/FA: Debug-level message logging enabled
W/olidon.bootcam: Class com.google.android.gms.tasks.zzn failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzl failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzh failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzm failed lock verification and will run slower.
D/FA: Resetting session stitching token to not null
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
W/olidon.bootcam: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/olidon.bootcam: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
V/FA: Activity resumed, time: 10481882
I/FA: Tag Manager is not found and thus will not be used
I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x7a5a40454410, tid 30270
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
W/OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
D/EGL_emulation: eglCreateContext: 0x7a5a40454290: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0x7a5a40454290: ver 2 0 (tinfo 0x7a5c5c125080) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0x7a5a40455c10, tid 30270
D/goldfish-address-space: allocate: Ask for block of size 0x100
D/goldfish-address-space: allocate: ioctl allocate returned offset 0x3efffe000 size 0x2000
W/Gralloc4: allocator 4.x is not supported
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 5
W/System: A resource failed to call close. 
V/FA: Inactivity, disconnecting from the service
D/ProfileInstaller: Installing profile for com.github.bjolidon.bootcamp
D/EGL_emulation: app_time_stats: avg=2210.36ms min=1.74ms max=19817.67ms count=9
V/FA: Recording user engagement, ms: 20188
V/FA: Connecting to remote service
V/FA: Connection attempt already in progress
V/FA: Activity paused, time: 10502072
V/FA: onActivityCreated
V/FA: Activity resumed, time: 10502145
V/FA: Connection attempt already in progress
V/FA: Connection attempt already in progress
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 4
D/OpenGLRenderer: endAllActiveAnimators on 0x7a5ac046e6f0 (RippleDrawable) with handle 0x7a59d0480900
W/olidon.bootcam: Class com.google.android.gms.internal.measurement.zzbz failed lock verification and will run slower.
D/EGL_emulation: app_time_stats: avg=215.64ms min=13.88ms max=1948.45ms count=10
V/FA: Recording user engagement, ms: 2358
V/FA: onActivityCreated
V/FA: Activity paused, time: 10504503
V/FA: Activity resumed, time: 10504562
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 141
V/FA: Activity paused, time: 10504703
V/FA: onActivityCreated
W/olidon.bootcam: Class com.google.android.gms.common.api.GoogleApiClient failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.api.internal.GoogleApiManager failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.internal.GmsClientSupervisor failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.GoogleApiAvailability failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzv failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.internal.BaseGmsClient failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.internal.zzr failed lock verification and will run slower.
V/FA: Activity resumed, time: 10504780
W/olidon.bootcam: Class com.google.android.gms.common.internal.zzo failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.api.internal.BasePendingResult failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzj failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.common.internal.zzc failed lock verification and will run slower.
W/olidon.bootcam: Class com.google.android.gms.tasks.zzi failed lock verification and will run slower.
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 228
V/FA: Activity paused, time: 10505008
V/FA: onActivityCreated
V/FA: Activity resumed, time: 10505082
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 137
V/FA: Activity paused, time: 10505219
V/FA: onActivityCreated
V/FA: Activity resumed, time: 10505259
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 95
V/FA: Activity paused, time: 10505354
D/CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10149; state: ENABLED
W/GoogleSignInHandler: Developer error: this application is misconfigured. Check your SHA1 and package name in the Firebase console.
E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
        at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:114)
        at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
        at android.app.Activity.dispatchActivityResult(Activity.java:8385)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
        at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:114)
        at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
        at android.app.Activity.dispatchActivityResult(Activity.java:8385)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
V/FA: Activity resumed, time: 10507125
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 54
V/FA: Activity paused, time: 10507180
E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
        at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:114)
        at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
        at android.app.Activity.dispatchActivityResult(Activity.java:8385)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5333)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5379)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
V/FA: Activity resumed, time: 10507199
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 18
V/FA: Activity paused, time: 10507217
V/FA: Activity resumed, time: 10507241
V/FA: onActivityCreated
V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 4
V/FA: Activity paused, time: 10507245
V/FA: Activity resumed, time: 10507287

**Comment by Bjolidon** [comment]
Issue fixed. Works properly on @KelvinKappeler phone. Let me know if the issue persists for you.
