### ISSUE TITLE
FilterActivity with connectedCheck

### ISSUE THREAD

**Issue by KelvinKappeler** [Tarjetakuna/Tarjetakuna#21]
**Problem**
When we launch a ConnectedCheck on Gradle, it often happens that some / the majority of Filter activity tests do not work. See the image in reference to see the problem and the error (this is the same error for each test). It is not always the same filter tests that do not work.

**What did I do**
Restart Android Studio, restart the phone, I tested on my physical phone, Wipe the data of the phone, reinstall the application, but nothing to do: always the same problem.

**What could be the problem**
The tests seem to be going too fast. It looks like it should be added thread.sleep (?) Between certain interactions.

<img width="1844" alt="image" src="https://user-images.githubusercontent.com/56725868/227732658-54c2a47a-8aa5-4825-8a7a-947b4cd26442.png">

**Comment by Cocograal** [comment]
Would you be able to tell me what steps you did in order to trigger the error? Because I ran connectedCheck from my computer 5 times but did not get any error at all. (I was on your branch)
If it is when you commit it on github, would you be able to send me the videos of the tests from cirrus CI so that I can figure out the error?

**Comment by KelvinKappeler** [comment]
In the opinion of a supervisor, the problem is related to a race condition. Thread.sleep(100) should be replaced (and removed if there are any) for conditions like:

If this button is visible => we continue the tests
Otherwise => we retest X times if the button is visible.

For the answers to your questions:
1) I didn't do anything special. I just ran the tests.
2) I can't show you with Cirrus. However, seeing the connectedCheck, the test stops for 5 seconds before failing.

**Comment by jeamigue** [comment]
+ refactor enum and check if tests still pass (William knows)

**Comment by KelvinKappeler** [comment]
FilterFragment has been deleted by @Bjolidon because he created a new filter. Problem solved.
