### ISSUE TITLE
Implement the localDatabase as backbone server of our app data

### ISSUE THREAD

**Issue by KelvinKappeler** [Tarjetakuna/Tarjetakuna#46]
For now, all data that we have is either stored in the modelView or the sharedpref
We need a localDatabase that will hold data persistently accross the application. this will help for interacting with the WebApi, the Firebase and other io that we could have.

The database should store raw data as possible : 
1) list of cards
2) list of sets
3) per user information (name, firebase id, collections of cards)
4) other things ?

**Comment by Cocograal** [comment]
This has been done https://github.com/Tarjetakuna/Tarjetakuna/pull/68
