### ISSUE TITLE
Search user in database

### ISSUE THREAD

**Issue by Bjolidon** [Tarjetakuna/Tarjetakuna#86]
We should be able to find a given user by searching by its username.

**Comment by JulienDiTria** [comment]
i would refactor the database to look like this : 

table of users:
- id (Primary key given by firebase authentication)
- username
- email (maybe not needed here)
- list of cards
	- cards id 
	- wanted
	- owned
- location
	- lat
	- long
- list of chat
	- chat id

table of cards:
- card id
- card details... 

table of chats
- chat id
- messages list 
	- message id
- user 1
- user 2

table of messages
- message id
- from user
- to user
- content as text
- timestamp

**Comment by annierusu** [comment]
This is an estimated time as it was done at the same time as the refactoring of the database.
